// ALIAS RELATED
export const ALIASES_MAP_KEY = 'ALIASES_MAP_KEY';
export const PROPERTY_ALIASES_KEY = 'PROPERTY_ALIASES_KEY';

// COMPOSITE KEYS RELATED
export const COMPOSITE_FIELD_KEY = 'COMPOSITE_FIELD_KEY';
export const COMPOSITE_DELIMITER_KEY = 'COMPOSITE_DELIMITER_KEY';

// PROP RELATED
export const PROP_FIELD_KEY = 'PROP_FIELD_KEY';
export const PRIMARY_FIELD_KEY = 'PRIMARY_FIELD_KEY';
export const SECONDARY_FIELD_KEY = 'SECONDARY_FIELD_KEY';
export const CREATED_AT_FIELD_KEY = 'CREATED_AT_FIELD_KEY';
export const UPDATED_AT_FIELD_KEY = 'UPDATED_AT_FIELD_KEY';

// RELATIONS RELATED
export const RELATIONS_MAP_KEY = 'RELATIONS_MAP_KEY';
export const FOREIGN_KEYS_MAP_KEY = 'FOREIGN_KEYS_MAP_KEY';
export const PARENT_FOREIGN_KEYS_MAP_KEY = 'PARENT_FOREIGN_KEYS_MAP_KEY';
export const CHILD_PROPERTIES_KEY = 'CHILD_PROPERTIES_KEY';

// TABLE RELATED
export const DYNAMODB_KEY = 'DYNAMODB_KEY';
export const TABLE_KEY = 'TABLE_KEY';

// VALIDATION RELATED
export const FIELD_VALIDATION_MAP_KEY = 'FIELD_VALIDATION_MAP_KEY';
export const MODEL_VALIDATION_MAP_KEY = 'MODEL_VALIDATION_MAP_KEY';
