name: Publish Package to npmjs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: 8398a7/action-slack@v3
        with:
          author_name: by ${{ github.event.pusher.name }}
          status: ${{ job.status }}
          text: Starting publish of Joiful Dynamo to NPM
          fields: repo,commit,ref,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_WEBHOOK_URL }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
      - name: Generate Package
        run: pnpm build
      - name: Configure npm
        run: pnpm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
      - name: Publish Package
        run: pnpm publish --access public
      - uses: 8398a7/action-slack@v3
        with:
          author_name: by ${{ github.event.pusher.name }}
          status: ${{ job.status }}
          text: Publish of Joiful Dynamo to NPM finished.
          # fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          fields: repo,commit,ref,job,took
          mention: U025BND74BY
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
